import { getLanguage } from './i18n.js';

export const products = [
  {
    id: "sprouted-ragi-flour",
    name: "Sprouted Ragi Flour",
    nameTa: "முளைகட்டிய ராகி மாவு",
    botanicalName: "Traditional Finger Millet",
    botanicalNameTa: "பாரம்பரிய ராகி தானியம்",
    category: "Grains & Flours",
    categoryTa: "தானியங்கள் & மாவு",
    price: 249.00,
    rating: 4.9,
    reviewsCount: 128,
    badge: "Best Seller",
    badgeTa: "அதிகம் விரும்பப்பட்டது",
    description: "Naturally sprouted for 48 hours to make digestion gentle and easy, then slowly stone-ground in small batches. Packed with natural calcium, plant-based iron, and a rich nutty flavor.",
    descriptionTa: "48 மணி நேரம் இயற்கை முறையில் முளைகட்டி, பாரம்பரிய கல் திரிகையில் மெதுவாக அரைக்கப்பட்டது. உடலுக்கு தேவையான இயற்கை கால்சியம் மற்றும் இரும்புச்சத்து நிறைந்தது.",
    details: "Sourced directly from family farms in Karnataka. Sprouting removes heaviness, leaving a nutritious flour that cooks quickly and digests light on your stomach.",
    detailsTa: "பாரம்பரிய இயற்கை விவசாயிகளிடமிருந்து நேரடியாக பெறப்பட்டது. முளைகட்டுவதால் வாயுத்தொல்லை இன்றி எளிதில் செரிமானமாகும்.",
    ingredients: "100% Certified Organic Sprouted Ragi (Finger Millet). Stone-ground. No preservatives, no added chemicals.",
    ingredientsTa: "100% இயற்கை முறையில் முளைகட்டிய ராகி. கல் திரிகையில் அரைக்கப்பட்டது. ரசாயனம் மற்றும் பதப்படுத்தும் பொருட்கள் அற்றது.",
    ritual: "Whisk 2 tablespoons into warm milk or water with a spoon of jaggery or honey for a quick, healthy breakfast drink.",
    ritualTa: "2 தேக்கரண்டி மாவை வெதுவெதுப்பான பால் அல்லது நீரில் நாட்டுச்சர்க்கரையுடன் கலந்து சத்தான காலை பானமாக பருகலாம்.",
    purity: "Tested in certified labs for zero chemical pesticides and 100% gluten-free purity.",
    purityTa: "ரசாயன உரங்கள் மற்றும் பூச்சிக்கொல்லிகள் இல்லாதது என ஆய்வகத்தில் சான்றளிக்கப்பட்டது.",
    sustainability: "Packed in recyclable, eco-friendly kraft paper pouches.",
    sustainabilityTa: "மக்கும் தன்மையுடைய சூழலுக்கு உகந்த பேக்கிங்.",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1000&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1000&q=85"
    ],
    benefits: ["Easy Digestion", "Daily Health", "Energy"],
    benefitsTa: ["எளிய செரிமானம்", "தினசரி நலம்", "உடல் ஆற்றல்"],
    sizes: ["500g Pouch", "1kg Value Pack"],
    sizesTa: ["500 கிராம் பை", "1 கிலோ குடும்ப பேக்"],
    featured: true
  },
  {
    id: "abc-detox-elixir",
    name: "Cold-Pressed ABC Detox Juice",
    nameTa: "ஏபிசி டிடாக்ஸ் ஜூஸ்",
    botanicalName: "Apple, Beetroot & Carrot",
    botanicalNameTa: "ஆப்பிள், பீட்ரூட் & கேரட்",
    category: "Juices & Drinks",
    categoryTa: "பழச்சாறுகள் & பானங்கள்",
    price: 189.00,
    rating: 4.8,
    reviewsCount: 94,
    badge: "100% Cold-Pressed",
    badgeTa: "100% கோல்ட்-பிரெஸ்ட்",
    description: "Freshly squeezed Apple, Beetroot, and Carrot juice with a hint of ginger. No added water, no added sugar, and never heated, preserving all natural vitamins.",
    descriptionTa: "ஆப்பிள், பீட்ரூட் மற்றும் கேரட் சாறுடன் இஞ்சி கலந்தது. தண்ணீர், சர்க்கரை மற்றும் வெப்பம் சேர்க்காமல் இயற்கை சத்துக்களுடன் தயாரிக்கப்பட்டது.",
    details: "Cold-pressed with hydraulic pressure to retain vitamins and natural antioxidants that help refresh your skin and support daily liver cleansing.",
    detailsTa: "ஹைட்ராலிக் முறையில் பிழியப்பட்டு இயற்கை ஆன்டிஆக்ஸிடன்ட்கள் மற்றும் வைட்டமின்கள் மாறாமல் பாதுகாக்கப்படுகிறது.",
    ingredients: "Organic Beetroot (40%), Fresh Crisp Apples (35%), Sweet Carrots (20%), Fresh Ginger (5%).",
    ingredientsTa: "ஆர்கானிக் பீட்ரூட் (40%), ஆப்பிள் (35%), கேரட் (20%), இஞ்சி (5%).",
    ritual: "Drink chilled in the morning before breakfast for a natural boost of daily energy.",
    ritualTa: "காலை உணவுக்கு முன் அருந்தினால் உடலுக்கு புத்துணர்ச்சியும் ஆற்றலும் கிடைக்கும்.",
    purity: "Zero preservatives, zero added sugar, 100% pure raw fruit and vegetable juice.",
    purityTa: "100% தூய பழம் மற்றும் காய்கறி சாறு.",
    sustainability: "Delivered in reusable amber glass bottles.",
    sustainabilityTa: "மறுபயன்பாடு செய்யக்கூடிய கண்ணாடி பாட்டில்களில் வழங்கப்படுகிறது.",
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=1000&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1000&q=85"
    ],
    benefits: ["Immunity", "Energy", "Daily Health"],
    benefitsTa: ["நோய் எதிர்ப்பு சக்தி", "உடல் ஆற்றல்", "தினசரி நலம்"],
    sizes: ["350ml Bottle", "Pack of 6 Cleanse Set"],
    sizesTa: ["350 மி.லி பாட்டில்", "6 பாட்டில் தொகுப்பு"],
    featured: true
  },
  {
    id: "golden-foxtail-millet",
    name: "Golden Foxtail Millet (Navane)",
    nameTa: "பாரம்பரிய தினை அரிசி",
    botanicalName: "Whole Grain Millet",
    botanicalNameTa: "முழு தானிய தினை",
    category: "Grains & Flours",
    categoryTa: "தானியங்கள் & மாவு",
    price: 225.00,
    rating: 4.9,
    reviewsCount: 76,
    badge: "Traditional Grain",
    badgeTa: "பாரம்பரிய தானியம்",
    description: "Naturally sun-dried whole grain millet with high fiber and low glycemic index. A light and healthy alternative to white rice for everyday meals.",
    descriptionTa: "சூரிய ஒளியில் உலர்த்தப்பட்ட தினை அரிசி. அதிக நார்ச்சத்து மற்றும் குறைந்த சர்க்கரை அளவு கொண்ட ஆரோக்கியமான உணவு.",
    details: "Grown naturally using rainwater without synthetic fertilizers. Keeps you full for longer and supports steady energy without post-meal sleepiness.",
    detailsTa: "மழைநீரை நம்பி இயற்கை முறையில் விளைவிக்கப்பட்டது. பசியைக் கட்டுப்படுத்தி உடலுக்கு நீண்ட நேர ஆற்றல் தரும்.",
    ingredients: "100% Organic Foxtail Millet. Unpolished and whole grain.",
    ingredientsTa: "100% தீட்டப்படாத ஆர்கானிக் தினை அரிசி.",
    ritual: "Cook just like rice! Simmer with water at a 1:2 ratio for 15 minutes for fluffy pulao, khichdi, or porridge.",
    ritualTa: "அரிசியைப் போலவே 1:2 அளவு தண்ணீர் சேர்த்து 15 நிமிடங்கள் வேகவைத்து சாதம், கிச்சடி அல்லது கஞ்சியாக சமைக்கலாம்.",
    purity: "Triple-cleaned and verified free from stones, dust, or chemicals.",
    purityTa: "தூசி, கல் இல்லாமல் மூன்று முறை சுத்தம் செய்யப்பட்டது.",
    sustainability: "Packed in breathable unbleached cotton pouches.",
    sustainabilityTa: "சுத்தமான பருத்தி பைகளில் பேக் செய்யப்பட்டது.",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=1000&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1000&q=85"
    ],
    benefits: ["Easy Digestion", "Energy"],
    benefitsTa: ["எளிய செரிமானம்", "உடல் ஆற்றல்"],
    sizes: ["1kg Pouch", "2.5kg Family Pack"],
    sizesTa: ["1 கிலோ பை", "2.5 கிலோ குடும்ப பேக்"],
    featured: true
  },
  {
    id: "hibiscus-wild-rose-tonic",
    name: "Hibiscus & Rose Herbal Cooler",
    nameTa: "செம்பருத்தி ரோஸ் மூலிகை பானம்",
    botanicalName: "Natural Floral Infusion",
    botanicalNameTa: "இயற்கை மலர் சாறு",
    category: "Juices & Drinks",
    categoryTa: "பழச்சாறுகள் & பானங்கள்",
    price: 320.00,
    rating: 5.0,
    reviewsCount: 63,
    badge: "Refreshing Cooler",
    badgeTa: "குளிர்ச்சி பானம்",
    description: "Sun-steeped natural red hibiscus flowers and fragrant organic rose petals, sweetened lightly with raw wildflower honey and pink salt.",
    descriptionTa: "செம்பருத்தி பூக்கள் மற்றும் காஷ்மீர் ரோஜா இதழ்களுடன் இயற்கை தேன் மற்றும் இந்துப்பு கலந்த புத்துணர்ச்சி பானம்.",
    details: "Naturally cooling for the body, high in natural Vitamin C, and delicious served chilled on warm afternoons.",
    detailsTa: "உடல் வெப்பத்தைத் தணித்து, வைட்டமின் சி சத்தை வழங்கும் சுவையான மூலிகை பானம்.",
    ingredients: "Purified Water, Organic Hibiscus Flowers, Damask Rose Water, Raw Honey, Pink Rock Salt.",
    ingredientsTa: "சுத்திகரிக்கப்பட்ட நீர், செம்பருத்தி பூக்கள், பன்னீர் ரோஜா, இயற்கை தேன், இந்துப்பு.",
    ritual: "Serve over ice with a slice of fresh lemon or mix with sparkling water for a refreshing mocktail.",
    ritualTa: "ஐஸ் கட்டிகள் மற்றும் எலுமிச்சை சாறுடன் கலந்து குளிர்ச்சியாக பருகலாம்.",
    purity: "100% natural herbal infusion with no artificial colors or artificial flavors.",
    purityTa: "செயற்கை நிறமிகள் அல்லது சுவையூட்டிகள் அற்றது.",
    sustainability: "Glass bottle with natural wooden cap.",
    sustainabilityTa: "மர மூடியுடன் கூடிய கண்ணாடி பாட்டில்.",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1000&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=1000&q=85"
    ],
    benefits: ["Daily Health", "Immunity"],
    benefitsTa: ["தினசரி நலம்", "நோய் எதிர்ப்பு சக்தி"],
    sizes: ["500ml Bottle", "1 Liter Family Bottle"],
    sizesTa: ["500 மி.லி பாட்டில்", "1 லிட்டர் குடும்ப பாட்டில்"],
    featured: false
  },
  {
    id: "amla-ashwagandha-drops",
    name: "Amla & Ashwagandha Daily Drops",
    nameTa: "நெல்லி & அஸ்வகந்தா மூலிகை துளிகள்",
    botanicalName: "Natural Herbal Extract",
    botanicalNameTa: "இயற்கை மூலிகை சாறு",
    category: "Wellness Drops",
    categoryTa: "மூலிகை துளிகள்",
    price: 599.00,
    rating: 4.9,
    reviewsCount: 89,
    badge: "Daily Immunity",
    badgeTa: "தினசரி நோய் எதிர்ப்பு",
    description: "A concentrated herbal blend of organic Ashwagandha root and fresh wild Amla. Helps reduce daily stress, calm the mind, and strengthen immunity.",
    descriptionTa: "அஸ்வகந்தா வேர் மற்றும் காட்டு நெல்லிக்காய் சாறு. மன அழுத்தத்தை குறைத்து, ஆழ்ந்த தூக்கத்திற்கும் நோய் எதிர்ப்பு சக்திக்கும் உதவுகிறது.",
    details: "Carefully extracted in plant glycerin and water. Highly concentrated so just a few drops daily support stamina and deep restful sleep.",
    detailsTa: "செறிவூட்டப்பட்ட இயற்கை சாறு. தினமும் சில துளிகள் உங்கள் உடல் வலிமையை அதிகரிக்கும்.",
    ingredients: "Organic Ashwagandha Root Extract, Wild Harvested Amla Extract, Organic Plant Glycerin, Purified Water.",
    ingredientsTa: "அஸ்வகந்தா வேர் சாறு, நெல்லிக்காய் சாறு, தாவர கிளிசரின், நீர்.",
    ritual: "Add 1 full dropper (about 20 drops) to a glass of warm water or herbal tea once or twice a day.",
    ritualTa: "வெதுவெதுப்பான நீர் அல்லது தேநீரில் 1 ட்ராப்பர் (20 துளிகள்) கலந்து பருகவும்.",
    purity: "Lab-tested for active herbal potency with zero alcohol and zero artificial additives.",
    purityTa: "ஆல்கஹால் இல்லாத 100% பாதுகாப்பான மூலிகை சாறு.",
    sustainability: "Amber glass dropper bottle.",
    sustainabilityTa: "கண்ணாடி ட்ராப்பர் பாட்டில்.",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1000&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1000&q=85"
    ],
    benefits: ["Immunity", "Energy", "Daily Health"],
    benefitsTa: ["நோய் எதிர்ப்பு சக்தி", "உடல் ஆற்றல்", "தினசரி நலம்"],
    sizes: ["60ml Dropper Bottle", "120ml Value Pack"],
    sizesTa: ["60 மி.லி பாட்டில்", "120 மி.லி தொகுப்பு"],
    featured: false
  },
  {
    id: "matcha-moringa-blend",
    name: "Organic Matcha & Moringa Tea",
    nameTa: "ஆர்கானிக் மட்சா & முருங்கை டீ",
    botanicalName: "Green Tea & Moringa Powder",
    botanicalNameTa: "கிரீன் டீ & முருங்கை இலை பொடி",
    category: "Juices & Drinks",
    categoryTa: "பழச்சாறுகள் & பானங்கள்",
    price: 749.00,
    rating: 4.8,
    reviewsCount: 52,
    badge: "Energy Booster",
    badgeTa: "ஆற்றல் தரும் பானம்",
    description: "Premium Japanese matcha green tea blended with fresh organic moringa leaf powder. Gives smooth, steady focus for work and study without jitters.",
    descriptionTa: "மட்சா கிரீன் டீ மற்றும் நாட்டு முருங்கை இலை பொடி கலவை. வேலை மற்றும் படிப்பில் கவனம் செலுத்த உதவும் புத்துணர்ச்சி டீ.",
    details: "Finely ground on stone wheels so it dissolves smoothly into warm water or milk with a creamy green froth.",
    detailsTa: "நுண்ணிய பொடியாக அரைக்கப்பட்டுள்ளதால் வெந்நீர் அல்லது பாலில் எளிதில் கரையும்.",
    ingredients: "100% Certified Organic Matcha Green Tea Powder, Organic Dried Moringa Leaf Powder.",
    ingredientsTa: "100% ஆர்கானிக் மட்சா கிரீன் டீ பொடி, உலர்ந்த முருங்கை இலை பொடி.",
    ritual: "Whisk 1 teaspoon into warm water or oat milk until frothy. Enjoy hot or iced as a morning drink.",
    ritualTa: "1 தேக்கரண்டி பொடியை சூடான நீரில் அல்லது பாலில் நன்கு கலந்து பருகவும்.",
    purity: "100% pure organic tea blend, tested free from heavy metals and pesticides.",
    purityTa: "பூச்சிக்கொல்லிகள் அற்ற 100% தூய ஆர்கானிக் டீ.",
    sustainability: "Airtight reusable tin to keep powder fresh.",
    sustainabilityTa: "மறுபயன்பாட்டுக்கு உகந்த காற்றுப்புகா டின் பேக்கிங்.",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=1000&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=1000&q=85"
    ],
    benefits: ["Energy", "Daily Health"],
    benefitsTa: ["உடல் ஆற்றல்", "தினசரி நலம்"],
    sizes: ["100g Tin", "250g Pouch"],
    sizesTa: ["100 கிராம் டின்", "250 கிராம் பை"],
    featured: false
  },
  {
    id: "artisanal-clay-vessel",
    name: "Handmade Terracotta Water Pot",
    nameTa: "கைவினை களிமண் தண்ணீர் பாத்திரம்",
    botanicalName: "Natural Earthen Clay",
    botanicalNameTa: "இயற்கை ஆற்று களிமண்",
    category: "Earthen Kitchenware",
    categoryTa: "களிமண் பாத்திரங்கள்",
    price: 899.00,
    rating: 5.0,
    reviewsCount: 41,
    badge: "Handmade Clay",
    badgeTa: "கைவினை தயாரிப்பு",
    description: "Handcrafted by local potters from natural river clay. Naturally cools your drinking water and adds healthy minerals without needing electricity.",
    descriptionTa: "மண்பாண்ட கலைஞர்களால் இயற்கை களிமண்ணில் செய்யப்பட்டது. தண்ணீரை இயற்கையாக குளிர்வித்து ஆரோக்கியமான தாதுக்களை சேர்க்கிறது.",
    details: "Clay has tiny natural micro-pores that allow water to evaporate slowly, keeping it naturally cold, fresh, and sweet tasting.",
    detailsTa: "களிமண்ணின் நுண்துளைகள் நீரை குளிர்ச்சியாகவும், சுவையாகவும் வைத்திருக்க உதவுகின்றன.",
    ingredients: "100% Natural Riverbed Clay. Lead-free and unglazed.",
    ingredientsTa: "100% இயற்கை களிமண். ஈயம் மற்றும் ரசாயனம் அற்றது.",
    ritual: "Rinse with water before first use. Fill with filtered drinking water and enjoy naturally cool, mineral-rich water all day.",
    ritualTa: "முதல் பயன்பாட்டிற்கு முன் தண்ணீரில் கழுவி, பின் குடிநீரை ஊற்றி வைத்து பயன்படுத்தலாம்.",
    purity: "Tested 100% lead-free, non-toxic, and food-grade safe.",
    purityTa: "உணவு பாதுகாப்பு சோதனை செய்யப்பட்டு சான்றளிக்கப்பட்டது.",
    sustainability: "Made purely from natural earth.",
    sustainabilityTa: "100% இயற்கையான மண் தயாரிப்பு.",
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1000&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1000&q=85"
    ],
    benefits: ["Daily Health"],
    benefitsTa: ["தினசரி நலம்"],
    sizes: ["1.2 Liters", "2.0 Liters"],
    sizesTa: ["1.2 லிட்டர்", "2.0 லிட்டர்"],
    featured: false
  },
  {
    id: "sprouted-millet-crunch",
    name: "Sprouted Millet Energy Crunch",
    nameTa: "முளைகட்டிய கம்பு எனர்ஜி ஸ்நாக்ஸ்",
    botanicalName: "Sprouted Millet & Jaggery Snack",
    botanicalNameTa: "கம்பு & நாட்டுச்சர்க்கரை சிற்றுண்டி",
    category: "Healthy Snacks",
    categoryTa: "ஆரோக்கிய சிற்றுண்டி",
    price: 175.00,
    rating: 4.7,
    reviewsCount: 38,
    badge: "Healthy Snack",
    badgeTa: "ஆரோக்கிய சிற்றுண்டி",
    description: "Crunchy roasted sprouted millet clusters sweetened with natural organic jaggery, coconut oil, and a pinch of cardamom. Perfect healthy tea-time snack.",
    descriptionTa: "முளைகட்டிய கம்பு, நாட்டுச்சர்க்கரை, தேங்காய் எண்ணெய் மற்றும் ஏலக்காய் கொண்டு வறுக்கப்பட்ட மொறுமொறுப்பான ஆரோக்கிய சிற்றுண்டி.",
    details: "A nutritious, guilt-free snack for kids and adults. No refined sugar, no palm oil, and 100% gluten-free.",
    detailsTa: "குழந்தைகளுக்கும் பெரியவர்களுக்கும் உகந்த ஊட்டச்சத்து நிறைந்த சிற்றுண்டி. பாமாயில் மற்றும் வெள்ளை சர்க்கரை இல்லாதது.",
    ingredients: "Sprouted Pearl Millet (Bajra), Organic Jaggery, Cold-Pressed Coconut Oil, Cardamom, White Sesame Seeds.",
    ingredientsTa: "முளைகட்டிய கம்பு, நாட்டுச்சர்க்கரை, தேங்காய் எண்ணெய், ஏலக்காய், வெள்ளை எள்.",
    ritual: "Enjoy straight out of the box with your evening cup of tea, or sprinkle over yogurt and fruit bowls.",
    ritualTa: "மாலை நேர தேநீருடன் அல்லது பழங்களுடன் சேர்த்து சாப்பிடலாம்.",
    purity: "Zero refined white sugar, zero palm oil, 100% gluten-free.",
    purityTa: "வெள்ளை சர்க்கரை மற்றும் பாமாயில் அற்றது.",
    sustainability: "Paper carton with biodegradable inner pouch.",
    sustainabilityTa: "மக்கும் பேக்கிங் பை.",
    image: "https://images.unsplash.com/photo-1514733670139-4d87a1941d55?auto=format&fit=crop&w=1000&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1514733670139-4d87a1941d55?auto=format&fit=crop&w=1000&q=85"
    ],
    benefits: ["Easy Digestion", "Energy"],
    benefitsTa: ["எளிய செரிமானம்", "உடல் ஆற்றல்"],
    sizes: ["250g Box", "Pack of 3 Boxes"],
    sizesTa: ["250 கிராம் பெட்டி", "3 பெட்டிகள் தொகுப்பு"],
    featured: false
  }
];

export function getLocalizedProduct(p) {
  if (!p) return null;
  const isTa = getLanguage() === 'ta';
  return {
    ...p,
    name: (isTa && p.nameTa) ? p.nameTa : p.name,
    botanicalName: (isTa && p.botanicalNameTa) ? p.botanicalNameTa : p.botanicalName,
    category: (isTa && p.categoryTa) ? p.categoryTa : p.category,
    badge: (isTa && p.badgeTa) ? p.badgeTa : p.badge,
    description: (isTa && p.descriptionTa) ? p.descriptionTa : p.description,
    details: (isTa && p.detailsTa) ? p.detailsTa : p.details,
    ingredients: (isTa && p.ingredientsTa) ? p.ingredientsTa : p.ingredients,
    ritual: (isTa && p.ritualTa) ? p.ritualTa : p.ritual,
    purity: (isTa && p.purityTa) ? p.purityTa : p.purity,
    sustainability: (isTa && p.sustainabilityTa) ? p.sustainabilityTa : p.sustainability,
    benefits: (isTa && p.benefitsTa) ? p.benefitsTa : p.benefits,
    sizes: (isTa && p.sizesTa) ? p.sizesTa : p.sizes
  };
}

export const getProductById = (id) => {
  const p = products.find(prod => prod.id === id);
  return getLocalizedProduct(p);
};

export const getFeaturedProducts = () => {
  return products.filter(p => p.featured).map(getLocalizedProduct);
};

export const getLocalizedProducts = () => {
  return products.map(getLocalizedProduct);
};
